[Data]
; Path to the validation/test dataset root directory
DatasetDir = ../data/testing
ImageSize = 128
; Number of workers for dataloader
NumWorkers = 12
; Batch size for evaluation (Keep small if memory is limited)
BatchSize = 12

[Model]
; Path to the trained model checkpoint (.pt)
CheckpointPath = ./training_logs/best_model.pth
; Path to the model configuration file
ModelConfigPath = model_config.ini

[Evaluation]
; Number of samples per image to generate for metrics
NumSamples = 4
; Sampling algorithm [choices -> DDPM, DDIM]
Sampler = DDIM

[Device]
; Device to use [cpu, cuda, cuda:0, etc.]
Device = cuda
